name: Deploy-Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: "8.2"
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: |
          docker build \
          --pull \
          --no-cache \
          --tag ${{ secrets.DOCKER_HUB_USERNAME }}/laravel-docker-base:latest \
          --tag ${{ secrets.DOCKER_HUB_USERNAME }}/laravel-docker-base:8.2 .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push tag(s) to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/laravel-docker-base:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/laravel-docker-base:8.2
      
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
